### ISSUE TITLE
[BUG] Errors with furnace, smoker, brewing, etc.

### ISSUE THREAD

**Issue by pacificminer** [ItsSchatten/PortableCraftingInvs#21] opened 2021-06-25 14:15 UTC
Hello. The following console errors are spammed in the console when using /brewing, /furnace, and /smoker.  This is on the latest Paper 1.17 (build 46) and plugin version 1.6.2. A fix would be much appreciated. Thank you

Error: https://pastebin.com/F821ZtUg

**Comment by ItsSchatten** [comment] 2021-06-26 01:04
This is such a strange issue that I'm half wondering if this is caused by Spigot. I experienced this issue in my test environment but I also got to be resolved using the same methods that I'm currently using.

I'll see if I can do something to stop the error from being logged to the console though.

**Comment by ItsSchatten** [comment] 2021-06-26 02:27
I've released an update to Spigot that should at minimum hide the error. If you're still getting the error please let me know.

**Comment by lewismercer** [comment] 2021-06-26 11:02
Im still getting this bug on the latest version.

**Comment by ItsSchatten** [comment] 2021-06-30 19:02
Marking this as resolved, should this actually not be resolved please reopen this issue.

**Closed by ItsSchatten** 2021-06-30 19:02 UTC
Labels: priority: normal, status: resolved, type: bug
